name = "tomasz-agencja-fun"
main = "src/worker.js"
compatibility_date = "2026-08-23"

# Dev: auto-deploy on push → tomasz-agencja-fun-dev.wojdatomek.workers.dev
[env.dev]
name = "tomasz-agencja-fun-dev"

# Prod: on manual trigger → route on tomasz.agencja.fun
[env.production]
name = "tomasz-agencja-fun"
routes = [
  { pattern = "tomasz.agencja.fun/*", zone_id = "6fec91fdd4edaf98891fab84bd60bb9d" }
]
