name = "tomasz-agencja-fun"
main = "src/worker.js"
compatibility_date = "2026-09-12"
account_id = "7060bcc794845705d4fb6b59f879384c"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[env.dev]
name = "tomasz-agencja-fun-dev"

[env.production]
name = "tomasz-agencja-fun"
routes = [
  { pattern = "tomasz.agencja.fun/*", zone_id = "6fec91fdd4edaf98891fab84bd60bb9d" }
]
